{
  "markdown": "[Skip to content](https://openai.github.io/openai-agents-python/ref/voice/exceptions/#exceptions)\n\n# `Exceptions`\n\n### STTWebsocketConnectionError\n\nBases: `AgentsException`\n\nException raised when the STT websocket connection fails.\n\nSource code in `src/agents/voice/exceptions.py`\n\n|     |     |\n| --- | --- |\n| ```<br>4<br>5<br>6<br>7<br>8<br>``` | ```md-code__content<br>class STTWebsocketConnectionError(AgentsException):<br>    \"\"\"Exception raised when the STT websocket connection fails.\"\"\"<br>    def __init__(self, message: str):<br>        self.message = message<br>``` |",
  "metadata": {
    "viewport": "width=device-width,initial-scale=1",
    "favicon": "https://openai.github.io/openai-agents-python/images/favicon-platform.svg",
    "generator": "mkdocs-1.6.1, mkdocs-material-9.6.11",
    "title": "Exceptions - OpenAI Agents SDK",
    "language": "en",
    "scrapeId": "29c8d424-9885-49a2-85c9-9d3026525928",
    "sourceURL": "https://openai.github.io/openai-agents-python/ref/voice/exceptions/",
    "url": "https://openai.github.io/openai-agents-python/ref/voice/exceptions/",
    "statusCode": 200,
    "contentType": "text/html; charset=utf-8",
    "proxyUsed": "basic"
  }
}